// produtos.js
let produtos = [
    { nome: "Alface", preco: 3.00, disponivel: true },
    { nome: "Batata", preco: 3.90, disponivel: true },
    { nome: "Cenoura", preco: 4.50, disponivel: true },
    { nome: "Abobrinha", preco: 5.00, disponivel: true },
    { nome: "Tomate", preco: 6.50, disponivel: true },
    { nome: "Chuchu", preco: 3.50, disponivel: true },
    { nome: "Quiabo", preco: 8.50, disponivel: true },
    { nome: "Couve", preco: 3.50, disponivel: true },
    { nome: "Espinafre", preco: 4.00, disponivel: true },
    { nome: "Rúcula", preco: 4.50, disponivel: true },
    { nome: "Almeirão", preco: 3.50, disponivel: true },
    { nome: "Chicória", preco: 3.50, disponivel: true },
    { nome: "Alcega", preco: 5.00, disponivel: true },
    { nome: "Salsinha", preco: 2.50, disponivel: true },
    { nome: "Cebolinha", preco: 2.50, disponivel: true },
    { nome: "Beterraba", preco: 4.80, disponivel: true },
    { nome: "Berinjela", preco: 6.00, disponivel: true },
    { nome: "Pimentão", preco: 7.90, disponivel: true },
    { nome: "Mandioca", preco: 5.90, disponivel: true },
    { nome: "Maçã", preco: 5.50, disponivel: true },
    { nome: "Banana", preco: 5.90, disponivel: true },
    { nome: "Abacaxi", preco: 7.60, disponivel: true },
    { nome: "Manga", preco: 5.70, disponivel: true },
    { nome: "Melancia", preco: 3.80, disponivel: true },
    { nome: "Mamão", preco: 5.20, disponivel: true },
    { nome: "Morango", preco: 9.00, disponivel: true },
    { nome: "Laranja", preco: 3.30, disponivel: true },
    { nome: "Limão", preco: 4.75, disponivel: true },
    { nome: "Uva", preco: 11.40, disponivel: true },
    { nome: "Maracujá", preco: 4.75, disponivel: true },
    { nome: "Geleia de Morango", preco: 14.30, disponivel: true },
    { nome: "Geleia de Pimenta", preco: 15.70, disponivel: true },
    { nome: "Geleia de Goiaba", preco: 13.80, disponivel: true },
    { nome: "Geleia de Maracujá", preco: 14.25, disponivel: true },
    { nome: "Geleia de Frutas Vermelhas", preco: 15.25, disponivel: true },
    { nome: "Geleia de Uva", preco: 12.25, disponivel: true },
    { nome: "Doce de Leite", preco: 16.15, disponivel: true },
    { nome: "Creme de Amendoim", preco: 17.60, disponivel: true },
    { nome: "Creme de Avelã", preco: 18.90, disponivel: true },
    { nome: "Queijo Minas Frescal", preco: 26.60, disponivel: true },
    { nome: "Queijo Muçarela", preco: 35.15, disponivel: true },
    { nome: "Pão de Leite com Goiabada", preco: 3.80, disponivel: true },
    { nome: "Pão Francês", preco: 16.15, disponivel: true },
    { nome: "Pão de Leite", preco: 2.35, disponivel: true },
    { nome: "Coxinha de Frango", preco: 6.65, disponivel: true },
    { nome: "Esfirra de Carne", preco: 5.70, disponivel: true },
    { nome: "Enroladinho de Salsicha", preco: 6.20, disponivel: true },
    { nome: "Biscoito Amanteigado", preco: 9.50, disponivel: true },
    { nome: "Biscoito de Goiabada", preco: 10.45, disponivel: true }
  ];
  